export const projectData = [
  { key: "N/A", text: "N/A", value: "N/A" },
  {
    key: "COVID-Mask (EHD)",
    text: "COVID-Mask (EHD)",
    value: "COVID-Mask (EHD)",
  },
  { key: "Dwenguino", text: "Dwenguino", value: "Dwenguino" },
  { key: "AeroSpec", text: "AeroSpec", value: "AeroSpec" },
  { key: "Ammonia", text: "Ammonia", value: "Ammonia" },
  {
    key: "Aero Propulsion (Private)",
    text: "Aero Propulsion (Private)",
    value: "Aero Propulsion (Private)",
  },
  {
    key: "Aircraft Mechanics",
    text: "Aircraft Mechanics",
    value: "Aircraft Mechanics",
  },
  { key: "Fuzz", text: "Fuzz", value: "Fuzz" },
  { key: "STREAM Tools", text: "STREAM Tools", value: "STREAM Tools" },
  { key: "Gamification", text: "Gamification", value: "Gamification" },
  { key: "SUDOKU", text: "SUDOKU", value: "SUDOKU" },
  { key: "ECoS", text: "ECoS", value: "ECoS" },
  { key: "Udemy", text: "Udemy", value: "Udemy" },
  { key: "WEGO", text: "WEGO", value: "WEGO" },
  { key: "Arduino Sensors", text: "Arduino Sensors", value: "Arduino Sensors" },
  { key: "Growing Rod", text: "Growing Rod", value: "Growing Rod" },
  {
    key: "RV Vectors (Private)",
    text: "RV Vectors (Private)",
    value: "RV Vectors (Private)",
  },
  {
    key: "Computing Skills Building (CSB)",
    text: "Computing Skills Building (CSB)",
    value: "Computing Skills Building (CSB)",
  },
  {
    key: "Drowsy Driving Detection",
    text: "Drowsy Driving Detection",
    value: "Drowsy Driving Detection",
  },
  {
    key: "Technical Writing",
    text: "Technical Writing",
    value: "Technical Writing",
  },
  { key: "Social Media", text: "Social Media", value: "Social Media" },
  { key: "Leadership", text: "Leadership", value: "Leadership" },
  {
    key: "Control Panel Template",
    text: "Control Panel Template",
    value: "Control Panel Template",
  },
  { key: "DietSkan", text: "DietSkan", value: "DietSkan" },
  { key: "598 COVID", text: "598 COVID", value: "598 COVID" },
  {
    key: "Commercialization",
    text: "Commercialization",
    value: "Commercialization",
  },
  {
    key: "DC-to-DC Converter",
    text: "DC-to-DC Converter",
    value: "DC-to-DC Converter",
  },
  {
    key: "COVID-Sensor (Personal Exposure, AeroSpec)",
    text: "COVID-Sensor (Personal Exposure, AeroSpec)",
    value: "COVID-Sensor (Personal Exposure, AeroSpec)",
  },
  {
    key: "COVID-Filter (EHD)",
    text: "COVID-Filter (EHD)",
    value: "COVID-Filter (EHD)",
  },
  { key: "Stoma", text: "Stoma", value: "Stoma" },
  { key: "FEF Sensors", text: "FEF Sensors", value: "FEF Sensors" },
  { key: "Pesticides", text: "Pesticides", value: "Pesticides" },
];
